//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proftaakrepos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proftaakrepos.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Achternaam {
            get {
                return ResourceManager.GetString("Achternaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active requests.
        /// </summary>
        public static string ActieveAanvragen {
            get {
                return ResourceManager.GetString("ActieveAanvragen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Allemaal {
            get {
                return ResourceManager.GetString("Allemaal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string ApplicatieHeader {
            get {
                return ResourceManager.GetString("ApplicatieHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        public static string Basisinformatie {
            get {
                return ResourceManager.GetString("Basisinformatie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company settings.
        /// </summary>
        public static string Bedrijfsinstellingen {
            get {
                return ResourceManager.GetString("Bedrijfsinstellingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string Contactgegevens {
            get {
                return ResourceManager.GetString("Contactgegevens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Dag {
            get {
                return ResourceManager.GetString("Dag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day(s).
        /// </summary>
        public static string Dagen {
            get {
                return ResourceManager.GetString("Dagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive E-mail notifications.
        /// </summary>
        public static string EmailNotificaties {
            get {
                return ResourceManager.GetString("EmailNotificaties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Heads-up when being scheduled.
        /// </summary>
        public static string HeadsUp {
            get {
                return ResourceManager.GetString("HeadsUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string Herstel {
            get {
                return ResourceManager.GetString("Herstel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Huisnummer {
            get {
                return ResourceManager.GetString("Huisnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents.
        /// </summary>
        public static string Incidenten {
            get {
                return ResourceManager.GetString("Incidenten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidents.
        /// </summary>
        public static string IncidentenHeader {
            get {
                return ResourceManager.GetString("IncidentenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        public static string Inkomend {
            get {
                return ResourceManager.GetString("Inkomend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust settings.
        /// </summary>
        public static string Instellingen {
            get {
                return ResourceManager.GetString("Instellingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no active requests.
        /// </summary>
        public static string JouwVerzoeken {
            get {
                return ResourceManager.GetString("JouwVerzoeken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a shift.
        /// </summary>
        public static string KiesDienst {
            get {
                return ResourceManager.GetString("KiesDienst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorscheme.
        /// </summary>
        public static string Kleurenschema {
            get {
                return ResourceManager.GetString("Kleurenschema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last account activity.
        /// </summary>
        public static string LastActivity {
            get {
                return ResourceManager.GetString("LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Maand {
            get {
                return ResourceManager.GetString("Maand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month(s).
        /// </summary>
        public static string Maanden {
            get {
                return ResourceManager.GetString("Maanden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Niet {
            get {
                return ResourceManager.GetString("Niet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active incidents at this time.
        /// </summary>
        public static string NoActiveIncidents {
            get {
                return ResourceManager.GetString("NoActiveIncidents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notificaties {
            get {
                return ResourceManager.GetString("Notificaties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Paginas {
            get {
                return ResourceManager.GetString("Paginas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string Pauze {
            get {
                return ResourceManager.GetString("Pauze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postalcode.
        /// </summary>
        public static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Rollen {
            get {
                return ResourceManager.GetString("Rollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Rooster {
            get {
                return ResourceManager.GetString("Rooster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string RoosterHeader {
            get {
                return ResourceManager.GetString("RoosterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string Roostermaker {
            get {
                return ResourceManager.GetString("Roostermaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade requests.
        /// </summary>
        public static string RuilaanvragenHeader {
            get {
                return ResourceManager.GetString("RuilaanvragenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your traderequests.
        /// </summary>
        public static string ruilverzoeken {
            get {
                return ResourceManager.GetString("ruilverzoeken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create traderequests.
        /// </summary>
        public static string RuilverzoekenAanmaken {
            get {
                return ResourceManager.GetString("RuilverzoekenAanmaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive textmessages.
        /// </summary>
        public static string SMSNotificatie {
            get {
                return ResourceManager.GetString("SMSNotificatie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Straatnaam {
            get {
                return ResourceManager.GetString("Straatnaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        public static string Telefoonnummer {
            get {
                return ResourceManager.GetString("Telefoonnummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string Toegang {
            get {
                return ResourceManager.GetString("Toegang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access per role.
        /// </summary>
        public static string ToegangPerRol {
            get {
                return ResourceManager.GetString("ToegangPerRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade requests.
        /// </summary>
        public static string TradeRequests {
            get {
                return ResourceManager.GetString("TradeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertions.
        /// </summary>
        public static string Tussenvoegsel {
            get {
                return ResourceManager.GetString("Tussenvoegsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing.
        /// </summary>
        public static string Uitgaand {
            get {
                return ResourceManager.GetString("Uitgaand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence.
        /// </summary>
        public static string Verlof {
            get {
                return ResourceManager.GetString("Verlof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request absence.
        /// </summary>
        public static string VerlofAanvragen {
            get {
                return ResourceManager.GetString("VerlofAanvragen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired requests.
        /// </summary>
        public static string VerlopenAanvragen {
            get {
                return ResourceManager.GetString("VerlopenAanvragen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string VoegToe {
            get {
                return ResourceManager.GetString("VoegToe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Voornaam {
            get {
                return ResourceManager.GetString("Voornaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password requirements.
        /// </summary>
        public static string WachtwoordVereisten {
            get {
                return ResourceManager.GetString("WachtwoordVereisten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week(s).
        /// </summary>
        public static string Weken {
            get {
                return ResourceManager.GetString("Weken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Wel {
            get {
                return ResourceManager.GetString("Wel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Werknemer {
            get {
                return ResourceManager.GetString("Werknemer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Werknemers {
            get {
                return ResourceManager.GetString("Werknemers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string WerknemersHeader {
            get {
                return ResourceManager.GetString("WerknemersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add employee.
        /// </summary>
        public static string WerknemerToevoegen {
            get {
                return ResourceManager.GetString("WerknemerToevoegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Wijzig {
            get {
                return ResourceManager.GetString("Wijzig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change data.
        /// </summary>
        public static string WijzigGegevens {
            get {
                return ResourceManager.GetString("WijzigGegevens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Woonplaats {
            get {
                return ResourceManager.GetString("Woonplaats", resourceCulture);
            }
        }
    }
}
