//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proftaakrepos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proftaakrepos.Resources.lang-nl", typeof(lang_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedrijfsinstellingen.
        /// </summary>
        public static string Bedrijfsinstellingen {
            get {
                return ResourceManager.GetString("Bedrijfsinstellingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidenten.
        /// </summary>
        public static string Incidenten {
            get {
                return ResourceManager.GetString("Incidenten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inkomend.
        /// </summary>
        public static string Inkomend {
            get {
                return ResourceManager.GetString("Inkomend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooster.
        /// </summary>
        public static string Rooster {
            get {
                return ResourceManager.GetString("Rooster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegang.
        /// </summary>
        public static string Toegang {
            get {
                return ResourceManager.GetString("Toegang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitgaand.
        /// </summary>
        public static string Uitgaand {
            get {
                return ResourceManager.GetString("Uitgaand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werknemers.
        /// </summary>
        public static string Werknemers {
            get {
                return ResourceManager.GetString("Werknemers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg werknemer toe.
        /// </summary>
        public static string WerknemerToevoegen {
            get {
                return ResourceManager.GetString("WerknemerToevoegen", resourceCulture);
            }
        }
    }
}
